"""add_roles

Revision ID: d856f00d0fcd
Revises: 686cac570f09
Create Date: 2023-11-12 17:55:03.572946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d856f00d0fcd"
down_revision: Union[str, None] = "686cac570f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "users",
        sa.Column(
            "roles",
            sa.Enum("admin", "moderator", "user", name="role"),
            nullable=True,
            default="user",
        ),
    )
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE role")
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
